// For NUODB

/**
 * Ensure a database is available and check versions of NuoDB database and
 * associated JARs.
 */
public class CheckNuoDBDatabaseAndVersion {

	/** User home directory */
	public static final String USER_HOME_PROPERTY = 'user.home';

	public String nuodbHibernateJarVersion;
	public double nuodbVersion;
	public SimpleDatabaseVersion nuodbDatabaseVersion;

	private final Class nuodbDataSourceClass;

	public CheckNuoDBDatabaseAndVersion(Class nuodbDataSourceClass) {
		this.nuodbDataSourceClass = nuodbDataSourceClass;
	}

	/**
	 * Initialize an instance and perform validation checks.
	 */
    public CheckNuoDBDatabaseAndVersion validate(String nuodbJdbcJarVersion, var project, String databasesGradleFile) {
		String testDirectory = project.projectDir;
		println '------- NuoDB Checks START -------'

        // Enable debugging comments in the SQL generated by NuoDB's Dialect
        System.setProperty('ENABLE_TRACE_COMMENTS', 'true');

		// Log project information
        println('Project details ...')
        println  "  Root project: ${project.rootProject}";
        println  "       rootDir: ${project.rootDir}"
        println  "    projectDir: ${project.projectDir}";
        println  "      user.dir: ${System.getProperty("user.dir")}";
        println  "      JDBC JAR: nuodb-jdbc-${nuodbJdbcJarVersion}"

        // Get and check NuoDB versions, check test database is running.
        check(nuodbJdbcJarVersion, project.projectDir);
        checkDatabase(new File(project.rootDir, databasesGradleFile));
		println '------- NuoDB Checks END -------'
		return this;
    }

	/**
	 * Look for JAR dependencies - these tests take ages to compile and run. 
	 * This code attempts to find any obvious errors up front.
	 */
	public void check(var nuodbJdbcJarVersion, testDirectory) {
		println('Performing NuoDB version checks');

		// Find Maven repository directory
		String repoPath = System.getenv('ADDITIONAL_REPO');

		if (repoPath == null)
			repoPath = System.getProperty(USER_HOME_PROPERTY) + '/.m2/repository';

		File repoDir = new File(repoPath);

		if (!repoDir.exists() || !repoDir.isDirectory())
			throw new RuntimeException("Repository directory '${repoDir}' is not valid");

		// The JDBC version is set at the top of this file. Is it valid?
		File jdbcDir = new File(repoDir, "com/nuodb/jdbc/nuodb-jdbc/${nuodbJdbcJarVersion}");

		if (!jdbcDir.exists())
			throw new RuntimeException( "No such NuoDB JDBC version ${nuodbJdbcJarVersion}");

		// The Hibernate version should be passed from the environment. Is it valid?
		File hibDir = new File(repoDir, 'com/nuodb/hibernate/nuodb-hibernate');
		String expectedVersion = System.getenv('DIALECT_VERSION');

		if (expectedVersion == null)
			throw new RuntimeException(
					'DIALECT_VERSION not set in environment (defines current NuoDB Hibernate Driver JAR Version');

		if (!expectedVersion.contains('-hib'))
			throw new RuntimeException(
					"DIALECT_VERSION should be of format 'x.x.x-hibN', such as '1.2.3-hib4'");

		String nuodbHibernateJarVersion = findInDirectory(hibDir, expectedVersion);

		if (!expectedVersion.equals(nuodbHibernateJarVersion))
			throw new RuntimeException(
					"DIALECT_VERSION set to ${expectedVersion}, but version not found in Maven repo");

		// The changelog's first line defines the Hibernate version. Does it match the NuoDB JAR?
		File changelogFile = new File(testDirectory, 'changelog.txt');

		if (!changelogFile.exists()) {
				println("  >> BUILD WARNING: Unable to find the project's 'changelog.txt' to confirm Hibernate version." 
					+ ' Make sure that DIALECT_VERSION is correct.' )
		}
		else {
			java.util.List lines = java.nio.file.Files.readAllLines(changelogFile.toPath());
			String line1 = lines.get(0);
			java.util.regex.Matcher matcher = java.util.regex.Pattern.compile('Hibernate (\\d+) Changelog').matcher(line1);

			if (matcher.matches()) {
				String majorVersionFromDir = matcher.group(1);
				println '  These tests are for Hibernate ' + majorVersionFromDir;

				// Get the version the JAR expects
				int ix = expectedVersion.indexOf('-hib')
				String majorVersion = expectedVersion.substring(ix + 4);
				println '  NuoDB Hibernate JAR is for Hibernate ' + majorVersion;

				// They must match
				if (!majorVersionFromDir.equals(majorVersion)) {
					throw new RuntimeException("BUILD FAILED: 'DIALECT_VERSION' incorrect, tests are for Hibernate " //
						+  "${majorVersionFromDir} but JAR nuodb-hibernate-${expectedVersion}" //
						+ " expects Hibernate ${majorVersion}" );
				}
			} else {
				println("  >> BUILD WARNING: Unable to determine Hibernate dialect from project's 'changelog.txt'." 
					+ ' Make sure that DIALECT_VERSION is correct.' )
			}
		}

		System.out.println('  NuoDB Hibernate JAR version = ' + nuodbHibernateJarVersion);
		this.nuodbHibernateJarVersion = nuodbHibernateJarVersion;
	}

	/**
	 * Look for the specified version in the Maven repository directory
	 */
	private String findInDirectory(File dir, String expectedVersion) {
		String latest = '';

		for (File versionDir : dir.listFiles()) {
			if (!versionDir.isDirectory())
				continue;

			String version = versionDir.getName();

			if (version.equals(expectedVersion))
				return version;

			if (version.compareTo(latest) > 0)
				latest = version;
		}

		return latest;
	}

    /**
	 * Check we can connect to a running database and get its product version.
	 *
	 * @param localDatabasesFilePath Location of the gradle file containing the
	 *                               connection details for all known databases.
	 */
	public void checkDatabase(String localDatabasesFilePath) {
		checkDatabase(new File(localDatabasesFilePath));
	}

	/**
	 * Can we connect to the database using the properties supplied? The tests
	 * run (but fail) even if a database is not available. This forces the build
	 * to stop.
	 *
	 * @param localDatabasesFile Location of the gradle file containing the connection
	 *                           details for all known databases.
	 */
	public void checkDatabase(File localDatabasesFile) {
		println('Checking a NuoDB database is available');
		java.util.Properties props = readDatabaseFile(localDatabasesFile);

		if (props.isEmpty()) {
			props.setProperty('db.dialect', 'com.nuodb.hibernate.NuoDBDialect');
			props.setProperty('jdbc.datasource' , 'com.nuodb.jdbc.DataSource');
			props.setProperty('jdbc.driver', 'com.nuodb.jdbc.Driver');
			props.setProperty('jdbc.url', ' jdbc:com.nuodb://localhost/hibernate_orm_test?isolation=read_committed&lock-wait-timeout=10');
			props.setProperty('jdbc.user', 'hibernate_orm_test');
			props.setProperty('jdbc.pass', 'hibernate_orm_test');
			println("  WARNING: Unable to load properties for NuoDB database from ${localDatabasesFile}");
		}

		// Build a database URL.  All we really need is the database name.
		String url = props.getProperty('jdbc.url');
		int ix = url.lastIndexOf('/');
		url = 'jdbc:com.nuodb://localhost' + url.substring(ix);
		//System.out.println('url = ' + url);

		java.util.Properties dbProps = new java.util.Properties();
		dbProps.setProperty('url', url);
		dbProps.setProperty('user', props.getProperty('jdbc.user'));
		dbProps.setProperty('password', props.getProperty('jdbc.pass'));
		//System.out.println(dbProps);

		javax.sql.DataSource dataSource =
			nuodbDataSourceClass.getConstructor(java.util.Properties.class).newInstance(dbProps)

		//com.nuodb.jdbc.DataSource dataSource = new com.nuodb.jdbc.DataSource(dbProps);

		// Check we can connect (database is running) and get the NuoDB version
		try (java.sql.Connection connection = dataSource.getConnection()) {
			System.out.println("  Connected to database URL: ${url}");

			// Database version info
			java.sql.DatabaseMetaData meta = connection.getMetaData();
			var dbVersion = meta.getDatabaseProductVersion();
			SimpleDatabaseVersion nuodbDatabaseVersion = new SimpleDatabaseVersion(dbVersion);
			this.nuodbVersion = (nuodbDatabaseVersion.major() * 10000) + (nuodbDatabaseVersion.minor() * 100)
					+ nuodbDatabaseVersion.micro();
			this.nuodbDatabaseVersion = nuodbDatabaseVersion;
			System.out.println("  NuoDB version ${nuodbDatabaseVersion} is available (${nuodbVersion})");
		} catch (java.sql.SQLException e) {
			String NL = System.lineSeparator();
			throw new RuntimeException('Failed to connect to a database - is it running?'
			        + NL + '    URL: ' + url
					+ NL + '  ERROR: ' + e.getLocalizedMessage() + ' (' + e.getClass().getSimpleName() + ')');
		}
	}

    /**
	 * Check we can connect to a running database and get its product version.
	 *
	 * @param localDatabasesFile Location of the gradle file containing the connection
	 *                           details for all known databases.
	 */
	public java.util.Properties readDatabaseFile(File localDatabasesFile) {
		// Check file actually exists
		if (!localDatabasesFile.exists())
			throw new RuntimeException("No such file: ${localDatabasesFile.getAbsolutePath}" );

		// Look for the NuoDB database connection properties in the file
		println("  Reading ${localDatabasesFile}")
		java.util.List<String> lines  = new ArrayList<>();

		try (java.io.BufferedReader rdr = new java.io.BufferedReader(new java.io.FileReader(localDatabasesFile))) {
			String line;

			while ((line = rdr.readLine()) != null)
				lines.add(line);
		} catch (java.io.IOException e) {
			throw new RuntimeException("Failed to read " + localDatabasesFile + ": " + e.getLocalizedMessage() + " (" + e.getClass().getSimpleName() + ")");
		}

		java.util.Properties props = new java.util.Properties();
		boolean save = false;

		for (String line : lines) {
			if (!save) {
				if (line.contains("nuodb")) {  // Start of NuoDB section
					save = true;
				}
				continue;
			}
			else if (line.contains("]"))
				break; // End of NuoDB section

			// Extract property
			line = line.replace('\'', ' ');

			if (line.endsWith(","))
				line = line.substring(0, line.length() - 1);

			int ix = line.indexOf(':');

			if (ix == -1)
				continue;

			String propName = line.substring(0, ix).trim();
			String propValue = line.substring(ix + 1).trim();
			props.setProperty(propName, propValue);
		}

		//System.out.println(props);
		return props;
	}
}
// END: For NUODB
