/*
 * Hibernate, Relational Persistence for Idiomatic Java
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */

buildscript {
    repositories {
        mavenCentral()
        mavenLocal()
        flatDir {
            dirs "${System.env['ADDITIONAL_REPO']}"
        }
    }
    dependencies {
        classpath 'com.nuodb.jdbc:nuodb-jdbc:${nuodbJdbcJarVersion}'
        classpath 'org.hibernate:hibernate-core:6.1.7.Final'
        classpath "com.nuodb.hibernate:nuodb-hibernate:${System.env['DIALECT_VERSION']}"
    }
}

// This should be set in build.gradle, let's just check ...
if (!properties.containsKey("nuodbJdbcJarVersion") || ext.nuodbJdbcJarVersion == null) {
    throw new GradleException("matrix.gradle: NuoDB JDBC JAR not available")
}

println "matrix.gradle: Build is using NuoDB Dialect  V${nuodbHibernateJarVersion}"

// Main purpose of this file is to set the JDBC JAR for NuoDB
jdbcDependency "com.nuodb.jdbc:nuodb-jdbc:${nuodbJdbcJarVersion}"
