# This is the default test database and credentials used by the tests in
# https://github.com/hibernate/hibernate-orm
url=jdbc:com.nuodb.hib://localhost/hibernate_orm_test?isolation=read_committed&lock-wait-timeout=10
username=hibernate_orm_test
password=hibernate_orm_test
driverClassName=com.nuodb.jdbc.Driver