/*
 * Hibernate, Relational Persistence for Idiomatic Java (5.6)
 *
 * License: GNU Lesser General Public License (LGPL), version 2.1 or later.
 * See the lgpl.txt file in the root directory or <http://www.gnu.org/licenses/lgpl-2.1.html>.
 */
 // HIBERNATE 5.6
import org.apache.tools.ant.filters.ReplaceTokens
import org.gradle.api.tasks.testing.TestResult.ResultType

// BEGIN: For NUODB V5
// Can't think of a way to make this generic, but we only test NuoDB
buildscript {
    repositories {
        mavenLocal()  // For NUODB JARs
        mavenCentral()
    }
    dependencies {
        classpath "com.nuodb.jdbc:nuodb-jdbc:${nuodbJdbcJarVersion}"
        classpath "com.nuodb.hibernate:nuodb-hibernate:${nuodbHibernateJarVersion}"
    }
}
// END: For NUODB

description = 'Hibernate\'s core ORM functionality'

apply from: rootProject.file( 'gradle/published-java-module.gradle' )
apply plugin: 'antlr'
apply plugin: 'hibernate-matrix-testing'
apply plugin: 'org.hibernate.build.gradle.xjc'

// BEGIN: For NUODB
println "hibernate-core: Using NuoDB Dialect from JAR V${nuodbHibernateJarVersion}"

//println "Runtime class path:"
//sourceSets.main.runtimeClasspath.each { println it}
// END: For NUODB

ext {
    jaxbTargetDir = file( "${buildDir}/generated-src/jaxb/main" )
}

sourceSets.main {
    java.srcDir project.jaxbTargetDir
}

sourceSets {
    // resources inherently exclude sources
    test {
        resources {
            srcDir 'src/test/java'
        }
    }
}

configurations {
    tests {
        description = 'Configuration for the produced test jar'
    }
}
// BEGIN: For NUODB - search local repo also
repositories {
	mavenCentral()
    mavenLocal()
}

// --------------------------------------------------------------------- //
// -         Control which tests are included or excluded 6.2          - //
// --------------------------------------------------------------------- //
test {
    filter {
        // ---------------------------------------------------------------------
        // Tests modified for NuoDB differences
        // ---------------------------------------------------------------------
        // NuoDB has a slightly different error message
        //   org.hibernate.orm.test.batch.BatchOptimisticLockingTest.testBatchAndOptimisticLocking
        // No space before + in NuoDB query hints
        //   org.hibernate.jpa.test.query.NamedQueryCommentTest
        // Expects trunc(x) but we replace trunc() by floor().
        //   org.hibernate.test.hql.HQLTest.testGroupByFunction

        // ---------------------------------------------------------------------
        // Failing tests that need fixing?
        // ---------------------------------------------------------------------

        // excludeTestsMatching 'org.hibernate.test.a*'
        // excludeTestsMatching 'org.hibernate.test.b*'
        // excludeTestsMatching 'org.hibernate.test.c*'
        // excludeTestsMatching 'org.hibernate.test.d*'
        // excludeTestsMatching 'org.hibernate.test.e*'
        // excludeTestsMatching 'org.hibernate.test.f*'
        // excludeTestsMatching 'org.hibernate.test.g*'
        // excludeTestsMatching 'org.hibernate.test.h*'
        // excludeTestsMatching 'org.hibernate.test.i*'
        // excludeTestsMatching 'org.hibernate.test.j*'
        // excludeTestsMatching 'org.hibernate.test.l*'
        // excludeTestsMatching 'org.hibernate.test.m*'
        // excludeTestsMatching 'org.hibernate.test.n*'
        // excludeTestsMatching 'org.hibernate.test.o*'
        // excludeTestsMatching 'org.hibernate.test.p*'
        // excludeTestsMatching 'org.hibernate.test.q*'
        // excludeTestsMatching 'org.hibernate.test.r*'
        // excludeTestsMatching 'org.hibernate.test.s*'
        // excludeTestsMatching 'org.hibernate.test.t*'
        // excludeTestsMatching 'org.hibernate.test.u*'
        // excludeTestsMatching 'org.hibernate.test.v*'
        // excludeTestsMatching 'org.hibernate.test.w*'

        // Undefined reference to DESCRIPTION
        // Too few values specified in the value list
        excludeTestsMatching 'org.hibernate.test.hql.BulkManipulationTest'

        // Runs fine manually
        excludeTestsMatching 'org.hibernate.jpa.test.lock.LockTest.testContendedPessimisticLock'
        excludeTestsMatching 'org.hibernate.test.typedescriptor.ByteTest.testByteDataPersistenceAndRetrieval'

        // expected:<x> but was:<y>
        excludeTestsMatching 'org.hibernate.test.hql.NaturalIdDereferenceTest.doNotDereferenceNaturalIdIfIsReferenceToPrimaryKey'
        excludeTestsMatching 'org.hibernate.test.hql.NaturalIdDereferenceTest.naturalIdDereferenceFromImplicitJoin'
        excludeTestsMatching 'org.hibernate.test.hql.NaturalIdDereferenceTest.naturalIdDereferenceTest'
        excludeTestsMatching 'org.hibernate.test.hql.NaturalIdDereferenceTest.nestedNaturalIdDereferenceFromImplicitJoin2'
        excludeTestsMatching 'org.hibernate.test.hql.NaturalIdDereferenceTest.normalIdDereferenceFromImplicitJoin'
        excludeTestsMatching 'org.hibernate.test.hql.NaturalIdDereferenceTest.selectedEntityIsNotDereferencedForPrimaryKey'

        excludeTestsMatching 'org.hibernate.test.cascade.circle.identity.CascadeCircleIdentityIdTest.testCascade'
            // org.junit.runners.model.TestTimedOutException at CascadeCircleIdentityIdTest.java:61
        excludeTestsMatching 'org.hibernate.test.annotations.cascade.multicircle.jpa.identity.MultiCircleJpaCascadeIdentityTest.testMerge'
            // org.junit.runners.model.TestTimedOutException at MultiCircleJpaCascadeIdentityTest.java:164
        excludeTestsMatching 'org.hibernate.test.annotations.cascade.multicircle.jpa.identity.MultiCircleJpaCascadeIdentityTest.testPersist'
            // org.junit.runners.model.TestTimedOutException at MultiCircleJpaCascadeIdentityTest.java:153
        excludeTestsMatching 'org.hibernate.test.annotations.cascade.multicircle.jpa.sequence.MultiCircleJpaCascadeSequenceTest.*' // 2/3 tests fail

        // Undefined table TOOL - 3/3 tests fail
        excludeTestsMatching 'org.hibernate.jpa.test.criteria.idclass.IdClassPredicateTest'

        // PreparedStatement is NOT closed
        excludeTestsMatching 'org.hibernate.jpa.test.lock.StatementIsClosedAfterALockExceptionTest.testStatementIsClosed'

        // unable to convert string "Jane Smith" into number
        excludeTestsMatching 'org.hibernate.test.inheritance.TransientOverrideAsPersistentJoined.testFindByRootClass'
        excludeTestsMatching 'org.hibernate.test.inheritance.TransientOverrideAsPersistentJoined.testFindBySubclass'
        excludeTestsMatching 'org.hibernate.test.inheritance.TransientOverrideAsPersistentJoined.testQueryByRootClass'
        excludeTestsMatching 'org.hibernate.test.inheritance.TransientOverrideAsPersistentJoined.testQueryBySublassAndOverridenProperty'
        excludeTestsMatching 'org.hibernate.test.inheritance.TransientOverrideAsPersistentTablePerClass'

        // Problems with Date and Time types
        excludeTestsMatching 'org.hibernate.test.type.LocalDateTest'
        excludeTestsMatching 'org.hibernate.test.temporal.TimePropertyTest.testTimeAsDate'
        excludeTestsMatching 'org.hibernate.test.timestamp.JdbcTimeCustomTimeZoneTest.testTimeZone'
        excludeTestsMatching 'org.hibernate.test.timestamp.JdbcTimestampCustomSessionLevelTimeZoneTest.testTimeZone'
        excludeTestsMatching 'org.hibernate.test.timestamp.JdbcTimestampCustomTimeZoneTest.testTimeZone'

        // Schema issues?
        excludeTestsMatching 'org.hibernate.test.schemaupdate.SchemaUpdateTest'

        // ---------------------------------------------------------------------
        // Tests to skip due to known NuoDB limitations
        // ---------------------------------------------------------------------

        // Does the NuoDB JDBC JAR support NClob, NString ... ?
        if (nuodbJdbcJarVersion.compareTo('24.2.2') < 0) {  // Supported from 24.2.2
            println 'hibernate-core.gradle: Excluding tests of Nationalized columns'
            excludeTestsMatching 'org.hibernate.test.criterion.NationalizedIgnoreCaseTest.testIgnoreCaseCriteria'
            excludeTestsMatching 'org.hibernate.orm.test.type.LobUnfetchedPropertyTest.testNClob'
            excludeTestsMatching 'org.hibernate.test.nationalized.NationalizedLobFieldTest.testNationalization'
            excludeTestsMatching 'org.hibernate.test.type.LobUnfetchedPropertyTest.testNClob'
        } else {
            println 'hibernate-core.gradle: Including tests of Nationalized columns'
        }

        if (nuodbHibernateJarVersion.compareTo('7.0.0') < 0) {
            println 'hibernate-core.gradle: Excluding tests using NuoDB 7 features'
        } else {
            println 'hibernate-core.gradle: Running tests using NuoDB 7 features'
        }
        
        // NuoDB does not use Catalogs
        excludeTestsMatching 'org.hibernate.test.boot.database.qualifiedTableNaming.DefaultCatalogAndSchemaTest'

        // all() not supported
        excludeTestsMatching 'org.hibernate.jpa.test.criteria.subquery.UncorrelatedSubqueryTest.testEqualAll'

        // ResultSets are forward only
        excludeTestsMatching 'org.hibernate.jpa.test.criteria.fetchscroll.CriteriaToScrollableResultsFetchTest.testWithScroll'
        excludeTestsMatching 'org.hibernate.test.criteria.SessionCreateQueryFromCriteriaTest.testScrollMethod'
        excludeTestsMatching 'org.hibernate.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesEmptyResultSet' // Before start of result set
        excludeTestsMatching 'org.hibernate.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesPositioning'
        excludeTestsMatching 'org.hibernate.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesReverse'
        excludeTestsMatching 'org.hibernate.test.hql.ScrollableCollectionFetchingTest.testScrollingJoinFetchesSingleRowResultSet'
        excludeTestsMatching 'org.hibernate.test.resulttransformer.ResultTransformerTest.testResultTransformerIsAppliedToScrollableResults'

        // Constraints not enforced
        excludeTestsMatching 'org.hibernate.jpa.test.exception.ExceptionTest.testConstraintViolationException'
        excludeTestsMatching 'org.hibernate.test.exception.SQLExceptionConversionTest.testIntegrityViolation' // INSERT should have failed

        // Referencial integrity not enforced
        excludeTestsMatching 'org.hibernate.test.manytomany.ManyToManyBidirectionalTest'

        //excludeTestsMatching 'org.hibernate.jpa.test.lock.LockTest.testContendedPessimisticLock'

        // SQL: '... where (x,y) IN ...' is not supported
        excludeTestsMatching 'org.hibernate.query.hhh14156.HHH14156Test'

        // multi-column value only allowed in comparison operators
        excludeTestsMatching 'org.hibernate.test.subselect.CompositeIdTypeBindingTest'

        // subqueries are not allowed in the ORDER BY clause
        excludeTestsMatching 'org.hibernate.test.hql.size.filter.WhereAnnotatedOneToManySizeTest.orderBy_dotSize'
        excludeTestsMatching 'org.hibernate.test.hql.size.filter.WhereAnnotatedOneToManySizeTest.orderBy_sizeOf'

        // Dependent Right Outer Join not supported
        excludeTestsMatching 'org.hibernate.test.join.OuterJoinTest.testJoinOrderWithRightJoinWithInnerImplicitJoins'

        // some(SELECT ...) not supported?  SOME() is equivalent to ANY()
        excludeTestsMatching 'org.hibernate.test.legacy.FooBarTest.testPersistCollections'
        excludeTestsMatching 'org.hibernate.test.legacy.FooBarTest.testQuery'
        excludeTestsMatching 'org.hibernate.test.legacy.SQLFunctionsTest.testSQLFunctions'
    }
}

dependencies {

    compile( libraries.jpa )
    // Could be made optional?
    compile( libraries.byteBuddy )
    compile( libraries.antlr )
    compile( libraries.jta )
    compile( libraries.jandex )
    compile( libraries.classmate )
    compile( libraries.activation )

    // NUODB: BEGIN
    compile( "com.nuodb.jdbc:nuodb-jdbc:${nuodbJdbcJarVersion}" )
    compile( "com.nuodb.hibernate:nuodb-hibernate:${nuodbHibernateJarVersion}" )
    // NUODB: END
    
    // We need dom4j for a number of things temporarily:
    //      1) (unsupported) EntityMode.DOM4J support
    //      2) Envers
    //      3) hibernate-commons-annotations
    //compile( libraries.dom4j ) ???
    compile( libraries.commons_annotations )
    antlr( libraries.antlr )

    // JAXB
    compile( libraries.jaxb_api )
    compile( libraries.jaxb_runtime )
    xjc( libraries.jaxb_runtime )
    xjc( libraries.jaxb_xjc )
    xjc( libraries.jaxb2_basics )
    xjc( libraries.jaxb2_basics_ant )
    xjc( libraries.activation )

    provided( libraries.jacc )
    provided( libraries.validation )
    provided( libraries.ant )
    provided( libraries.cdi )

    testCompile( project(':hibernate-testing') )
    testCompile( libraries.shrinkwrap_api )
    testCompile( libraries.shrinkwrap )
    testCompile( libraries.jacc )
    testCompile( libraries.validation )
    testCompile( libraries.jandex )
    testCompile( libraries.classmate )
    testCompile( libraries.mockito )
    testCompile( libraries.mockito_inline )
    testCompile( libraries.jodaTime )
    testCompile( libraries.assertj )

    testCompile( libraries.cdi )

    testCompile( libraries.validator ) {
        // for test runtime
        transitive = true
    }

    // for testing stored procedure support
    testCompile( libraries.derby )

    testRuntimeOnly( "org.jboss.spec.javax.ejb:jboss-ejb-api_3.2_spec:1.0.0.Final" )
    testRuntimeOnly( libraries.expression_language )
    testRuntimeOnly( 'jaxen:jaxen:1.1' )
    testRuntimeOnly( libraries.byteBuddy )
    testRuntimeOnly( libraries.weld )
    testRuntimeOnly( libraries.atomikos )
    testRuntimeOnly( libraries.atomikos_jta )
    testRuntimeOnly( libraries.wildfly_transaction_client )

    // NUODB: BEGIN
    testRuntimeOnly( "com.nuodb.hibernate:nuodb-hibernate:${nuodbHibernateJarVersion}" )
    testRuntimeOnly( "com.nuodb.jdbc:nuodb-jdbc:${nuodbJdbcJarVersion}" )
    // NUODB: END

    testAnnotationProcessor( project( ':hibernate-jpamodelgen' ) )

    testCompile libraries.shrinkwrap_descriptors_api_javaee
    testCompile libraries.shrinkwrap_descriptors_impl_javaee

    testCompile libraries.jboss_ejb_spec_jar
    testCompile libraries.jboss_annotation_spec_jar

    // Additional tests requiring Javassist
    // folder in src/javassist/java
    testCompile "com.nuodb.hibernate:nuodb-hibernate:${nuodbHibernateJarVersion}"
}

jar {
    manifest {
        attributes(
                'Main-Class': 'org.hibernate.Version',

                // BND Plugin instructions (for OSGi):
                'Import-Package': [
                        'javax.security.auth;resolution:=optional',
                        // Make javax.security.jacc optional and do not reference a version range (because that's what we used to do)
                        'javax.security.jacc;resolution:=optional;version=!',
                        // Make javax.validation optional and do not reference a version range (because that's what we used to do)
                        'javax.validation;resolution:=optional;version=!',
                        'javax.validation.constraints;resolution:=optional;version=!',
                        'javax.validation.groups;resolution:=optional;version=!',
                        'javax.validation.metadata;resolution:=optional;version=!',
                        // Make javax.enterprise optional and do not reference a version range (because that's what we used to do)
                        '!javax.enterprise*',
                        'javax.enterprise.context.spi;resolution:=optional;version=!',
                        'javax.enterprise.inject.spi;resolution:=optional;version=!',
                        // For JPA, we don't want to target the automatically generated range, but a specific version
                        "javax.persistence;version=\"${project.jpaVersion.osgiName}\"",
                        // optionals
                        'jakarta.persistence.spi;resolution:=optional',
                        'javax.management;resolution:=optional',
                        'javax.naming.event;resolution:=optional',
                        'javax.naming.spi;resolution:=optional',
                        'org.apache.tools.ant;resolution:=optional',
                        'org.apache.tools.ant.taskdefs;resolution:=optional',
                        'org.apache.tools.ant.types;resolution:=optional',
                        'javax.inject;resolution:=optional',
                        'net.bytebuddy.*;resolution:=optional',
                        'org.objectweb.jonas_tm;resolution:=optional',
                        'com.ibm.websphere.jtaextensions;resolution:=optional',
                        // We must specify the version explicitly to allow Karaf
                        // to use an older version of JAXB (the only one we can use in Karaf)
                        "javax.xml.bind.*;version=\"${project.jaxbApiVersionOsgiRange}\"",
                        // Temporarily support JTA 1.1 -- Karaf and other frameworks still
                        // use it.  Without this, the plugin generates [1.2,2).
                        'javax.transaction;version="[1.1,2)"',
                        // Also import every package referenced in the code
                        '*'
                ].join( ',' ),
                '-exportcontents': [
                        // Legacy resource packages containing XSDs that were traditionally not exported
                        "!org.hibernate.xsd.cfg",
                        "!org.hibernate.xsd.mapping",
                        // TODO: Uncomment once EntityManagerFactoryBuilderImpl no longer uses ClassLoaderServiceImpl.
                        //'org.hibernate.boot.registry.classloading.internal',
                        "*;version=${project.version}"
                ].join( ',' ),
        )
    }
}

//idea {
//	module {
//		sourceDirs += file( "${buildDir}/generated-src/antlr/main" )
//	}
//}

xjc {
    outputDir = project.jaxbTargetDir

    schemas {
        cfg {
            xsd = file( 'src/main/resources/org/hibernate/xsd/cfg/legacy-configuration-4.0.xsd' )
            xjcBinding = file( 'src/main/xjb/hbm-configuration-bindings.xjb' )
        }
        hbm {
            xsd = file( 'src/main/resources/org/hibernate/xsd/mapping/legacy-mapping-4.0.xsd' )
            xjcBinding = file( 'src/main/xjb/hbm-mapping-bindings.xjb' )
            xjcExtensions = ['inheritance', 'simplify']
        }
        mapping {
            xsd = file( 'src/main/resources/org/hibernate/jpa/orm_2_2.xsd' )
            xjcBinding = file( 'src/main/xjb/mapping-bindings.xjb' )
            xjcExtensions = ['inheritance']
        }
    }
}

generateGrammarSource {
    arguments += "-traceParser"
}

//sourceSets.main.sourceGeneratorsTask.dependsOn xjc
//sourceSets.main.sourceGeneratorsTask.dependsOn generateGrammarSource
tasks.compile.dependsOn generateGrammarSource

task copyBundleResources (type: Copy) {
    ext {
        bundleTokens = dbBundle[db]
        ext.bundleTokens['buildDirName'] = buildDir.absolutePath
    }

    from 'src/test/bundles/templates'
    into "${buildDir}/bundles"
    filter( ReplaceTokens, tokens: ext.bundleTokens)
}
processTestResources.dependsOn copyBundleResources

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

task testJar(type: Jar, dependsOn: testClasses) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier.set( 'test' )
    from sourceSets.test.output
    from( "${buildDir}/bundles" ) {
        into 'bundles'
    }
}

artifacts {
    tests testJar
}

test {
    systemProperty 'file.encoding', 'utf-8'

    if ( gradle.ext.javaVersions.test.launcher.asInt() >= 9 ) {
        // See org.hibernate.boot.model.naming.NamingHelperTest.DefaultCharset.set
        jvmArgs( ['--add-opens', 'java.base/java.nio.charset=ALL-UNNAMED'] )
        // Weld needs this to generate proxies
        jvmArgs( ['--add-opens', 'java.base/java.security=ALL-UNNAMED'] )
        jvmArgs( ['--add-opens', 'java.base/java.lang=ALL-UNNAMED'] )
    }

    // NUODB: Write runtime classpath to classpath.txt
    doFirst{
        String NL = System.lineSeparator;

        try {
            StringBuilder sb = new StringBuilder();
            File outputFile = new File("classpath.txt")
            println("Writing runtime class path to file: " + outputFile.getAbsolutePath())
            sb.append("Runtime classpath:").append(NL)
            sourceSets.main.runtimeClasspath.each { sb.append("    ").append(it).append(NL) }
            java.nio.file.Files.write(outputFile.toPath(), sb.toString().getBytes(),
                java.nio.file.StandardOpenOption.CREATE, java.nio.file.StandardOpenOption.TRUNCATE_EXISTING);
            println("File written OK")
            println(sb.toString())
        } catch (Exception e) {
            println("Failed to write file: " + e);
        }

        println("Running test")
    }
    // NUODB: END

    beforeTest { descriptor ->
        //println "Starting test: " + descriptor
    }
}