# Settings to run these tests against NuoDB
jpa.version=3.2.0
jakartaJpaVersion=${jpa.version}

nuodb.jdbc.version=24.2.1
nuodb.hibernate.version=24.0.0-hib7
nuodb.java.common.version=2.1.0

hibernate.version=7.2.4.Final
logback.version=1.4.14
slf4j.version=2.0.17
